#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /
    controller: App\Controller\FrontController::index

histoires:
    path: /histoires
    controller: App\Controller\FrontController::listeHistoires

histoire:
    path: /histoires/{id}
    controller: App\Controller\FrontController::showHistoire

entreprises:
    path: /entreprises
    controller: App\Controller\FrontController::listeEntreprises

entreprise:
    path: /entreprises/{id}
    controller: App\Controller\FrontController::showEntreprise

politiques:
    path: /politiques
    controller: App\Controller\FrontController::listePolitiques

politique:
    path: /politiques/{id}
    controller: App\Controller\FrontController::showPolitique

planetes:
    path: /planetes
    controller: App\Controller\FrontController::listePlanetes

planete:
    path: /planetes/{id}
    controller: App\Controller\FrontController::showPlanete

theme:
    path: /theme
    controller: App\Controller\FrontController::theme

view_theme:
    path: theme/theme-view
    controller: App\Controller\FrontController::themeView

create_post:
    path: /post/new
    controller: App\Controller\FormsController::formPost

update_post:
    path: /post/{id}/edit
    controller: App\Controller\FormsController::formPost

registration:
    path: /registration
    controller: App\Controller\SecurityController::registration

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

administration:
    path: /administration
    controller: App\Controller\BackController::administation

view_members:
    path: /view_members
    controller: App\Controller\BackController::viewMembers

profil_user:
    path: /profil
    controller: App\Controller\BackController::profil

apropos:
    path: /propos
    controller: App\Controller\FrontController::propos

terms:
    path: /terms
    controller: App\Controller\FrontController::terms

vie_prive:
    path: /vie-prive
    controller: App\Controller\FrontController::viePrive

cookies_info:
    path: /cookies
    controller: App\Controller\FrontController::cookieSite